title = "Thomas Han"
baseURL = "https://thomashan.xyz/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Dallas, TX"
email = "dxh2764@gmail.com"
favicon = "/favicon.ico"
firstName = "Thomas"
lastName = "Han"
phone = "469-682-7506"
profileImage = "img/thomas.jpeg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = false
showQr = false
showSkills = true

[params.google]

[params.google.analytics]
trackerID = ""

[[params.handles]]
link = "https://www.linkedin.com/in/thomas-han1209"
name = "LinkedIn"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
