[build]
	publish = "public" 
	command = "hugo -D"

[build.environment]
	HUGO_VERSION = "0.73.0"

[context.production.environment]
	HUGO_VERSION = "0.73.0"
	HUGO_ENV = "production"
	HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
	HUGO_VERSION = "0.73.0"
